# Generated by Django 3.2.6 on 2021-08-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0003_alter_action_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='action',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
