# Generated by Django 3.2.6 on 2021-08-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0004_auto_20210818_2253'),
        ('Action', '0004_auto_20210819_1938'),
    ]

    operations = [
    ]
