# Generated by Django 3.2.6 on 2021-08-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'ordering': ['-created_at']},
        ),
    ]
