# Generated by Django 3.2.6 on 2021-08-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0002_alter_logger_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='reference',
            field=models.IntegerField(default=0, verbose_name='Reference ID'),
        ),
    ]
