# Generated by Django 3.2.6 on 2021-08-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodyType', '0001_initial'),
        ('ComponentType', '0003_alter_componenttype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='body_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BodyType.bodytype', verbose_name='Body type'),
        ),
    ]
