# Generated by Django 3.2.6 on 2021-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComponentType', '0006_alter_componenttype_is_inner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttype',
            name='is_inner',
            field=models.BooleanField(choices=[(1, 'inside'), (0, 'outside')], null=True, verbose_name='Is inner'),
        ),
    ]
