# Generated by Django 3.2.6 on 2021-08-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Color', '0001_initial'),
        ('BodyType', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending', max_length=255, verbose_name='State')),
                ('pin', models.CharField(max_length=255, verbose_name='PIN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BodyType.bodytype', verbose_name='Body type')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Color.color', verbose_name='Color')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
