# Generated by Django 3.2.6 on 2021-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='sent_at',
            field=models.DateTimeField(null=True, verbose_name='Sent at'),
        ),
    ]
