# Generated by Django 3.2.6 on 2021-08-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_auto_20210819_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='blueprint_inside',
            field=models.ImageField(null=True, upload_to='reports/', verbose_name='Blueprint inside'),
        ),
        migrations.AddField(
            model_name='report',
            name='blueprint_outside',
            field=models.ImageField(null=True, upload_to='reports/', verbose_name='Blueprint outside'),
        ),
    ]
