# Generated by Django 3.2.6 on 2021-08-25 00:29

import App.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_auto_20210822_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='blueprint_inside',
            field=models.ImageField(null=True, storage=App.storage.OverwriteStorage(), upload_to='reports/', verbose_name='Blueprint inside'),
        ),
        migrations.AlterField(
            model_name='report',
            name='blueprint_outside',
            field=models.ImageField(null=True, storage=App.storage.OverwriteStorage(), upload_to='reports/', verbose_name='Blueprint outside'),
        ),
    ]
