# Generated by Django 3.2.6 on 2021-08-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Point', '0001_initial'),
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Report.report', verbose_name='Report'),
        ),
    ]
