# Generated by Django 3.2.6 on 2021-08-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0002_point_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='location',
        ),
    ]
