# Generated by Django 3.2.6 on 2021-08-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InclusionType', '0002_alter_inclusiontype_marker'),
        ('ErrorType', '0002_alter_errortype_marker'),
        ('Point', '0004_auto_20210815_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('stage', models.IntegerField(null=True, verbose_name='Stage')),
                ('error_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_type_summary', to='ErrorType.errortype', verbose_name='Error type')),
                ('inclusion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_type_summary', to='InclusionType.inclusiontype', verbose_name='Inclusion type')),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
    ]
