# Generated by Django 3.2.6 on 2021-08-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='date_end',
            field=models.DateTimeField(verbose_name='Date end'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='date_start',
            field=models.DateTimeField(verbose_name='Date start'),
        ),
    ]
